default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: overtime_development
  username: <%= Rails.application.credentials.db_development_username %>
  password: <%= Rails.application.credentials.db_development_password %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: overtime_test
  # You may need to bring in the actual values if running db commands as Rails will not resolve the test and dev credentials at the same time 
  username: <%= Rails.application.credentials.db_test_username %>
  password: <%= Rails.application.credentials.db_test_password %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: overtime_production
